version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install:
          node-version: '18'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /workspace
       - add_ssh_keys:
          fingerprints:
            - "ec:81:5f:4b:e2:09:6d:63:11:5c:65:46:f2:27:98:51"
      - run:
          name: Copy dist folder to Server
          command: scp -a /workspace/dist/* $SSH_USER@$SSH_HOST:/var/www/html/via-app

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
