version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /root/via-app && git stash && git pull && which npm && npm run refresh-kbs && npm run build:vite && cp -a ./dist/. /var/www/html/via-app"

# Orchestrate our job run sequence
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
